// src/data.js — complete data file for SAATHI prototype
// All hardcoded content lives here. Import from this file — never duplicate data inline in pages.

// ─── COMPANION OPTIONS ───────────────────────────────────────────────────────
export const COMPANIONS = [
  { id: 'owl',      emoji: '🦉', name: 'Gyaan',   description: 'Loves words and stories',      sldDefault: 'dyslexia' },
  { id: 'fox',      emoji: '🦊', name: 'Chiku',   description: 'Quick and clever',              sldDefault: null },
  { id: 'elephant', emoji: '🐘', name: 'Moti',    description: 'Never forgets anything!',       sldDefault: 'dyscalculia' },
  { id: 'turtle',   emoji: '🐢', name: 'Dheeraj', description: 'Steady and sure always wins',   sldDefault: null },
  { id: 'lion',     emoji: '🦁', name: 'Bahadur', description: 'Brave and bold',                sldDefault: null },
  { id: 'parrot',   emoji: '🦜', name: 'Mithu',   description: 'Expressive and creative',       sldDefault: 'dysgraphia' },
];

// ─── DEMO STUDENT DATA ────────────────────────────────────────────────────────
export const DEMO_STUDENTS = [
  {
    id: 'student_001',
    name: 'Arjun',
    class: 4,
    school: 'GPS Barmer, Rajasthan',
    sldType: 'dyslexia',
    severity: 'moderate',
    language: 'HI',
    lastActive: '2 hours ago',
    streakDays: 4,
    status: 'green',
    companion: { id: 'owl', emoji: '🦉', nickname: 'Gyaan' },
    masteryMap: {
      'CVC Words': 'mastered',
      'Rhyming Words': 'in_progress',
      'Sight Words (50)': 'in_progress',
      'Syllable Splitting': 'mastered',
      'Sentence Reading': 'not_started',
      'Short Passage Reading': 'struggling',
    },
    errorPatterns: [
      { pattern: 'b/d reversal', frequency: '7 of 10 instances', trend: 'improving' },
      { pattern: 'Word omission while reading aloud', frequency: '4 of 10 passages', trend: 'stable' },
      { pattern: "Reads 'was' as 'saw'", frequency: '3 of 10 instances', trend: 'improving' },
    ],
    weeklyStats: { timeSpent: '1h 23m', activitiesCompleted: 7, helpRequests: 3 },
    aiSuggestion: "Arjun responds better to oral assessments. His comprehension scores are strong when audio support is on — consider oral examination instead of written this week.",
    progressHistory: [62, 58, 55, 48],
  },
  {
    id: 'student_002',
    name: 'Priya',
    class: 6,
    school: 'Municipal School, Pune, Maharashtra',
    sldType: 'dyscalculia',
    severity: 'mild-moderate',
    language: 'EN',
    lastActive: '1 day ago',
    streakDays: 2,
    status: 'yellow',
    companion: { id: 'elephant', emoji: '🐘', nickname: 'Moti' },
    masteryMap: {
      'Counting to 20': 'mastered',
      'Single-digit Addition': 'mastered',
      'Double-digit Addition': 'struggling',
      'Subtraction with Borrowing': 'not_started',
      'Place Value': 'in_progress',
      'Multiplication (x2, x5)': 'not_started',
    },
    errorPatterns: [
      { pattern: 'Loses place value with numbers > 2 digits', frequency: '6 of 10 tasks', trend: 'stable' },
      { pattern: 'Digit transposition (writes 21 for 12)', frequency: '4 of 10 tasks', trend: 'improving' },
    ],
    weeklyStats: { timeSpent: '45m', activitiesCompleted: 4, helpRequests: 5 },
    aiSuggestion: "Priya struggles when abstract symbols appear before the visual model. Always show object-based counting before symbolic notation in her activities.",
  },
  {
    id: 'student_003',
    name: 'Rohit',
    class: 5,
    school: 'GPS Varanasi, UP',
    sldType: 'dyslexia',
    severity: 'mild',
    language: 'HI',
    lastActive: '8 days ago',
    streakDays: 0,
    status: 'red',
    companion: { id: 'fox', emoji: '🦊', nickname: 'Chiku' },
    masteryMap: {
      'CVC Words': 'mastered',
      'Rhyming Words': 'mastered',
      'Sight Words (50)': 'in_progress',
      'Syllable Splitting': 'in_progress',
      'Sentence Reading': 'in_progress',
      'Short Passage Reading': 'in_progress',
    },
    errorPatterns: [
      { pattern: 'p/q reversal', frequency: '5 of 10 instances', trend: 'stable' },
      { pattern: 'Word skipping in long sentences', frequency: '3 of 10 passages', trend: 'worsening' },
    ],
    weeklyStats: { timeSpent: '0m', activitiesCompleted: 0, helpRequests: 0 },
    aiSuggestion: "Rohit has been inactive for 8 days. A brief personal encouragement often re-engages students. His last session showed good progress in sight words.",
  },
];

// ─── READING CONTENT ──────────────────────────────────────────────────────────
export const READING_CONTENT = [
  {
    id: 'read_001',
    title: 'The Clever Crow',
    titleHI: 'चतुर कौआ',
    language: 'EN',
    gradeLevel: 4,
    text: 'It was a hot summer day. A crow was very thirsty. He looked for water everywhere. At last, he found a pot. The pot had very little water in it. The crow could not reach the water. He thought and thought. Then he had a clever idea. He picked up small stones one by one. He put them into the pot. Slowly the water came up. The crow drank the water and flew away happily.',
    textHI: 'एक बार एक कौआ था। उसे बहुत प्यास लगी थी। वह पानी की तलाश में इधर-उधर उड़ा। कहीं पानी नहीं मिला। तभी उसे एक घड़ा दिखा। घड़े में थोड़ा-सा पानी था। कौआ पानी तक नहीं पहुँच सकता था। उसने सोचा। फिर उसे एक तरकीब सूझी। उसने एक-एक करके कंकड़ उठाए। उसने सारे कंकड़ घड़े में डाले। पानी ऊपर आ गया। कौए ने पानी पीया और उड़ गया।',
    syllabledWords: {
      'everywhere': 'ev-ery-where',
      'clever': 'clev-er',
      'thirsty': 'thirs-ty',
      'slowly': 'slow-ly',
      'happily': 'hap-pi-ly',
      'water': 'wa-ter',
      'summer': 'sum-mer',
      'stones': 'stones',
    },
    comprehensionQuestions: [
      {
        question: 'Why was the crow looking for water?',
        questionHI: 'कौआ पानी क्यों ढूंढ रहा था?',
        options: [
          { text: 'He was hungry', emoji: '🍞' },
          { text: 'He was thirsty', emoji: '💧' },
          { text: 'He was playing', emoji: '⚽' },
          { text: 'He was lost', emoji: '🗺️' },
        ],
        correct: 1,
      },
      {
        question: 'What did the crow put into the pot?',
        questionHI: 'कौए ने घड़े में क्या डाला?',
        options: [
          { text: 'Sand', emoji: '🏖️' },
          { text: 'Leaves', emoji: '🍃' },
          { text: 'Small stones', emoji: '🪨' },
          { text: 'Sticks', emoji: '🪵' },
        ],
        correct: 2,
      },
      {
        question: 'How did the crow feel at the end?',
        questionHI: 'अंत में कौआ कैसा महसूस कर रहा था?',
        options: [
          { text: 'Sad', emoji: '😢' },
          { text: 'Angry', emoji: '😠' },
          { text: 'Happy', emoji: '😊' },
          { text: 'Scared', emoji: '😨' },
        ],
        correct: 2,
      },
    ],
  },
];

// ─── MATH CONTENT (NUMBER WORLD) ─────────────────────────────────────────────
export const MATH_ACTIVITIES = [
  {
    id: 'math_001',
    type: 'addition',
    title: 'Adding Apples',
    titleHI: 'सेब जोड़ो',
    leftCount: 3,
    rightCount: 4,
    emoji: '🍎',
    description: 'apples',
    descriptionHI: 'सेब',
    equation: '3 + 4 = 7',
    answer: 7,
  },
  {
    id: 'math_002',
    type: 'comparison',
    title: 'Which pile has more?',
    titleHI: 'कौन सा ढेर ज़्यादा है?',
    leftCount: 3,
    rightCount: 7,
    emoji: '🍊',
    correct: 'right',
  },
];

// ─── ACHIEVEMENT DATA ──────────────────────────────────────────────────────────
export const ACHIEVEMENTS = [
  { id: 'ach_001', icon: '🎯', title: 'You read 287 words this week!', titleHI: 'आपने इस हफ्ते 287 शब्द पढ़े!', category: 'reading' },
  { id: 'ach_002', icon: '⭐', title: 'Word of the Day — 5 days in a row!', titleHI: 'दिन का शब्द — 5 दिन लगातार!', category: 'streak' },
  { id: 'ach_003', icon: '📚', title: 'You finished 3 stories in Reading Room', titleHI: 'आपने पठन कक्ष में 3 कहानियाँ पूरी कीं', category: 'reading' },
  { id: 'ach_004', icon: '🔢', title: 'Number Town: 2 buildings completed!', titleHI: 'नंबर टाउन: 2 इमारतें पूरी!', category: 'maths' },
  { id: 'ach_005', icon: '🎤', title: 'You told 5 stories in Expression Studio', titleHI: 'आपने 5 कहानियाँ सुनाईं', category: 'expression' },
  { id: 'ach_006', icon: '🔥', title: '4-day learning streak! Keep going!', titleHI: '4 दिन की लर्निंग स्ट्रीक!', category: 'streak' },
];

// ─── RESOURCE LIBRARY ──────────────────────────────────────────────────────────
export const RESOURCES = [
  {
    id: 'res_001',
    title: 'Dyslexia Classroom Checklist',
    sldType: 'dyslexia',
    classLevel: 'All',
    type: 'Accommodation Guide',
    description: 'Step-by-step classroom accommodation checklist for teachers supporting dyslexic students.',
    rating: 4,
    preview: `DYSLEXIA CLASSROOM ACCOMMODATION CHECKLIST\n\nSeating: Place the student near the front, away from distractions.\nFont: Use OpenDyslexic or Arial 14pt+ in all printed materials.\nAssessment: Offer oral examination as an alternative to written tests.\nTime: Provide 1.5x extended time on all timed tasks.\nReading: Allow use of a finger or ruler as a line guide.\nNote-taking: Provide printed notes rather than requiring board copying.\nEncouragement: Acknowledge effort verbally every session.`,
  },
  {
    id: 'res_002',
    title: 'Object-Based Maths Lesson Plan',
    sldType: 'dyscalculia',
    classLevel: '3–6',
    type: 'Lesson Plan',
    description: 'Step-by-step lesson plan for teaching addition and subtraction using physical objects before symbols.',
    rating: 5,
    preview: `OBJECT-BASED MATHS LESSON — CLASS 3-6\n\nLesson Goal: Teach 2-digit addition using physical grouping.\n\nStep 1: Use 10-20 physical counters (bottle caps, stones, or beans).\nStep 2: Ask student to group counters into two piles (e.g. 6 and 8).\nStep 3: Student physically counts total by moving each counter to a new pile.\nStep 4: Only after counting is complete, write the equation on paper: 6 + 8 = 14.\nStep 5: Repeat with different values. NEVER introduce symbols first.\n\nKey rule: Equation notation always follows physical experience. Never precedes it.`,
  },
  {
    id: 'res_003',
    title: 'Parent Communication Template — Dyslexia',
    sldType: 'dyslexia',
    classLevel: 'All',
    type: 'Parent Template',
    description: 'Plain-language letter to help teachers communicate an SLD finding to parents respectfully.',
    rating: 4,
    preview: `Dear Parent/Guardian,\n\nI am writing to share some observations about your child's learning that I believe will be helpful.\n\nYour child is a hardworking and enthusiastic student. I have noticed that they sometimes find reading and writing activities more challenging than other areas — this is not uncommon, and it does not reflect their intelligence or effort at all.\n\nI would like to discuss some learning support strategies that have helped many children. These are simple adjustments to how we present information that can make a significant difference.\n\nPlease feel free to contact me at your convenience. I look forward to working together for your child's success.\n\nWarm regards,\n[Teacher Name]`,
  },
  {
    id: 'res_004',
    title: 'Expression Studio Prompt Cards',
    sldType: 'dysgraphia',
    classLevel: '3–8',
    type: 'Activity Resource',
    description: 'Illustrated prompt cards for dysgraphic students to use voice or drawing instead of writing.',
    rating: 5,
    preview: `EXPRESSION STUDIO PROMPT CARDS\n\nHow to use: Show the student the illustrated prompt. Let them choose how to respond: speak their answer aloud, draw it, or arrange word tiles.\n\nPrompt 1: 🌳🚪✨ "Meera found a magical door in the forest. What was behind it?"\nPrompt 2: 🐘🌊🏃 "The elephant ran away from the river. Why was it scared?"\nPrompt 3: 🌙⭐🏠 "One night, a star fell into Raju's garden. What happened next?"\nPrompt 4: 🎒📚🎓 "On the last day of school, everyone got a surprise. What was it?"\n\nReminder: There is no wrong answer. Celebrate every response.`,
  },
];

// ─── UI STRINGS (EN / HI) ─────────────────────────────────────────────────────
export const STRINGS = {
  EN: {
    appName: 'Saath-i',
    tagline: 'Your journey to learning your way',
    startExploring: 'Start exploring',
    haveClassCode: 'I have a class code',
    todaysJourney: "Today's Journey",
    readingRoom: 'Reading Room',
    numberWorld: 'Number World',
    expressionStudio: 'Expression Studio',
    achievementWall: 'Achievement Wall',
    iAmStruggling: "I'm struggling",
    generateIEP: 'Generate IEP',
    teacherDashboard: 'Teacher Dashboard',
    offlineBanner: 'Offline mode — data will sync when connected',
    welcomeBack: 'Welcome back!',
    goodMorning: 'Good morning',
    continue: 'Continue',
    skip: 'Skip for now',
    letsDo: "Let's go!",
    chooseCompanion: 'Choose your learning buddy!',
    companionTagline: 'Your buddy will cheer you on every step of the way 🌟',
    learnerProfileReveal: "Based on how you played... 🌟 It looks like you're great at listening! We'll use lots of sounds in your learning.",
    screeningTitle: "Let's see how YOU like to learn! 🎮",
    breathe: "Let's take a breath 🌬️",
    tryEasier: 'Want to try something a bit easier first?',
    loginTitle: 'Teacher Dashboard',
    schoolCode: 'School Code',
    teacherName: 'Your Name',
    loginButton: 'Login as Teacher',
  },
  HI: {
    appName: 'साथी',
    tagline: 'अपने तरीके से सीखने की यात्रा',
    startExploring: 'शुरू करें',
    haveClassCode: 'मेरे पास क्लास कोड है',
    todaysJourney: 'आज की यात्रा',
    readingRoom: 'पठन कक्ष',
    numberWorld: 'संख्या जगत',
    expressionStudio: 'अभिव्यक्ति स्टूडियो',
    achievementWall: 'उपलब्धि दीवार',
    iAmStruggling: 'मुझे मदद चाहिए',
    generateIEP: 'IEP बनाएं',
    teacherDashboard: 'शिक्षक डैशबोर्ड',
    offlineBanner: 'ऑफलाइन मोड — कनेक्ट होने पर डेटा सिंक होगा',
    welcomeBack: 'वापस स्वागत है!',
    goodMorning: 'सुप्रभात',
    continue: 'आगे बढ़ें',
    skip: 'अभी छोड़ें',
    letsDo: 'चलो शुरू करें!',
    chooseCompanion: 'अपना साथी चुनें!',
    companionTagline: 'आपका साथी हर कदम पर आपको प्रोत्साहित करेगा 🌟',
    learnerProfileReveal: 'आपने जैसे खेला उससे... 🌟 लगता है आप सुनने में बहुत अच्छे हैं! हम आपकी पढ़ाई में बहुत सारी आवाज़ें इस्तेमाल करेंगे।',
    screeningTitle: 'देखते हैं आपको सीखना कैसे पसंद है! 🎮',
    breathe: 'एक सांस लेते हैं 🌬️',
    tryEasier: 'क्या पहले कुछ आसान करना चाहेंगे?',
    loginTitle: 'शिक्षक डैशबोर्ड',
    schoolCode: 'स्कूल कोड',
    teacherName: 'आपका नाम',
    loginButton: 'शिक्षक के रूप में लॉगिन करें',
  },
};
